# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eme < Formula
  desc "Mission control for your AI coding agents — run each in its own git worktree + tmux session"
  homepage "https://eme.jinmu.me"
  version "0.1.1"
  license "MIT"

  depends_on "git"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alderwork/eme/releases/download/v0.1.1/eme_Darwin_x86_64.tar.gz"
      sha256 "97277c3f1852f7e1933c535b7b54956aec983f76bf9018ffc934f05e22a68add"

      define_method(:install) do
        bin.install "eme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alderwork/eme/releases/download/v0.1.1/eme_Darwin_arm64.tar.gz"
      sha256 "c157ccfb394aca392278a5f5c762921f4e4dd9a6a8f9982da50abef7f9491f25"

      define_method(:install) do
        bin.install "eme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alderwork/eme/releases/download/v0.1.1/eme_Linux_x86_64.tar.gz"
      sha256 "9709ecca5587457c40c12de4cb86801ef4989cc425e96f5622eabdef44df6221"
      define_method(:install) do
        bin.install "eme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alderwork/eme/releases/download/v0.1.1/eme_Linux_arm64.tar.gz"
      sha256 "c750212e0440d9cdae0103ba5a41e58ff5c98af32bafe7d43a4de875443a67db"
      define_method(:install) do
        bin.install "eme"
      end
    end
  end

  test do
    system "#{bin}/eme", "--version"
  end
end
