# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eme < Formula
  desc "Mission control for your AI coding agents — run each in its own git worktree + tmux session"
  homepage "https://eme.jinmu.me"
  version "0.1.3"
  license "MIT"

  depends_on "git"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alderwork/eme/releases/download/v0.1.3/eme_Darwin_x86_64.tar.gz"
      sha256 "27930985ed5e5f57f1ca106fa0bfa10e9537a12254cf518284ea7ed9f02ff42c"

      define_method(:install) do
        bin.install "eme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alderwork/eme/releases/download/v0.1.3/eme_Darwin_arm64.tar.gz"
      sha256 "013d937e4863e7807eacd7dc9ccedf2e0fce31b18ebe50ea809b8b1a707d8ce4"

      define_method(:install) do
        bin.install "eme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alderwork/eme/releases/download/v0.1.3/eme_Linux_x86_64.tar.gz"
      sha256 "503d9ca24459188c569addb57aa1e7568d432d0d4718e71e4ad3d2cc3b8f3c1e"
      define_method(:install) do
        bin.install "eme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alderwork/eme/releases/download/v0.1.3/eme_Linux_arm64.tar.gz"
      sha256 "e68eb3ad4996984b1e908435125bdc0dc76ec2b1b229ff2cc95a05dbbaf8d8f4"
      define_method(:install) do
        bin.install "eme"
      end
    end
  end

  test do
    system "#{bin}/eme", "--version"
  end
end
